### ISSUE TITLE
请适配transmission2.9x系列

### ISSUE THREAD

**Issue by i990049** [YemaPT-org/feedback#10]
目前国内外的pt只能使用bt1.0协议的种子，很多保种的客户端都是transmission，实测tr2.94不能使用，peer id是，希望适配，谢谢
-TR2940-

**Comment by mustangpt** [comment]
请提供tr错误截图以及种子id

**Comment by i990049** [comment]
刚才测试2.94已经可以下载最多人做种的文件，另外为什么不论手机电脑看论坛的帖子都是这样？
![Screenshot_20240611-022216](https://github.com/YemaPT-org/feedback/assets/103364093/942d8886-ef56-45cd-a082-7bf549444fa1)
