### ISSUE TITLE
qq邮箱无法收到验证邮件

### ISSUE THREAD

**Issue by dick86114** [YemaPT-org/feedback#2]
qq邮箱无法收到验证邮件，提示发送正常，实际上邮箱里找不到任何邮件

**Comment by ilike2burnthing** [comment]
How was this resolved for you? I am trying with Gmail, but I have not received an email yet.

您是如何解决这个问题的？我正在尝试使用 Gmail，但尚未收到电子邮件。

**Comment by dick86114** [comment]
> How was this resolved for you? I am trying with Gmail, but I have not received an email yet.
> 
> 您是如何解决这个问题的？我正在尝试使用 Gmail，但尚未收到电子邮件。

那时候是邮箱故障，第二天就好了，你等明后天再试试

**Comment by ilike2burnthing** [comment]
I misspelled my email address 🤦 

我的电子邮件地址拼错了 🤦
