### ISSUE TITLE
没有适配手机页面，切换桌面模式也不行

### ISSUE THREAD

**Issue by i990049** [YemaPT-org/feedback#5]
我用的手机浏览器是支持插件的狐猴浏览器，版本号2.4.1.001，这是狐猴最后一个没有广告的版本了。微软浏览器安卓版Edge 120.0.2210.99，两个手机浏览器就算切换到桌面模式不能显示野马pt种子下载页面的文件大小、下载中、做种中、发布时间这几个选项。馒头新架构也是JAVA，在我的手机上用前面那两个浏览器显示文件大小、下载中做种中、发布时间都没问题，不知道野马种子页面是不是w3c标准，外站AsiaDVDclub用的也是Markdown发布页，可以适配手机，还有跟文件大小成正比的弹性HR，建议站长去参考一下。

**Comment by mustangpt** [comment]
请提供具体页面截图

**Comment by i990049** [comment]
![Screenshot_20240609-110422](https://github.com/YemaPT-org/feedback/assets/103364093/1ef3ad65-9b6d-4fc2-a30a-3a80e4a7d2e7)

**Comment by i990049** [comment]
![Screenshot_20240609-231045](https://github.com/YemaPT-org/feedback/assets/103364093/22f285f2-b9b5-4db2-a4da-5605eaa4b6f7)
这是安卓微软浏览器版本Edge 125.0.2535.72，默认手机页面是不显示种子列表的，就算切换到桌面模式，还是看不到每个种子文件大小多少人保种多少人下载，用最新版本狐猴也一样。同样是Java架构的馒头用手机看没问题。

**Comment by mustangpt** [comment]
这是移动端自适应架构，手机屏幕小，为了展示更简洁，因此没有展示其他信息，后面会优化一版，增加上这些内容。

**Comment by mustangpt** [comment]
已处理
