### ISSUE TITLE
为什么搜索框不是全站搜索而是分类搜索？

### ISSUE THREAD

**Issue by i990049** [YemaPT-org/feedback#7]
别的站点搜个功夫熊猫4，电影类别也有，动漫类别也有；搜个张学友，所有的电影、音乐、演唱会类别全部出来了，野马pt要我去每个分类下面搜一次？先不说用户觉得啰嗦不啰嗦，以后要是用户多了，都这样搜几遍，服务器搜索压力不是更大？
PS：RSS订阅也不是全站一键订阅，既然发布选项有媒介、分辨率、视频、音频选项，应该把这些选项也加入RSS订阅，并且增加关键字选项订阅主标题副标题，比如RSS订阅关键字SDR或者1080p，订阅关键字CHD或者FRDS，建议学习unit3d架构增加永久免费标签定义，并且在副标题提示有弹性HR。
发种标签分类进一步细化，既然写了2160p/4K，那对应的应该写1080p/2K，视频编码有些老旧动画会用AVC 10bit，以后的编码会有H.266/VVC、华为三星高通的EVC，音频编码有些是opus或者flac，不想分那么细直接学地区分类给个other选项，电子书、有声书、音乐这些都没有视频的参数，应该在媒介、分辨率哪里添加other选项，制作组里面也加个other选项。
体育是跟纪录片、动漫平等的类别，应该把体育挪到影视版块，全部的版块再上一级类别才叫综合，现在野马的综合分类其实应该叫其他，把现在的其他分类删掉即可。现在缺的就是全站综合搜索和全站RSS关键字订阅。

**Comment by mustangpt** [comment]
感谢您对本站的关心，建议已经收到了。网站逐步完善中，您提到的部分功能已经迭代上线，其他功能也会根据网站建设方向和优先级而采纳支持。
再次感谢您的关心和建议~

**Comment by mustangpt** [comment]
已增加相关功能
