### ISSUE TITLE
request: API documentation

### ISSUE THREAD

**Issue by ilike2burnthing** [YemaPT-org/feedback#9]
Hi, I am one of the maintainers for Jackett, and we want to add support for your tracker.

I was trying to use your API endpoint `https://www.yemapt.org/api/torrent/fetchCategoryOpenTorrentList` with the cookie `auth=xxx`, but just always get `{"success":false,"showType":0}`.

Any help would be appreciated, thank you.

---

你好，我是 Jackett 的维护者之一，我们想为您的跟踪器添加支持。

我尝试使用您的 API 端点 `https://www.yemapt.org/api/torrent/fetchCategoryOpenTorrentList` 和 cookie `auth=xxx`，但总是得到 `{"success":false,"showType":0}`。

任何帮助都将不胜感激，谢谢。

**Comment by mustangpt** [comment]
At present, there is no dedicated API, so if connected, it can only be accessed through a web page interface. The fetchCategoryOpenTorrentList interface you mentioned currently requires the following:
1. Use the POST method to request
2. The JSON content of the request body must include categoryId and page size. The specific example is as follows:
```
{
    "categoryId": 4,
    "pageParam": {
        "current": 1,
        "pageSize": 20
    }
}
```

If you have more questions, you can leave a contact email and communicate through email.



------

目前没有专门的API，因此如果对接，目前只能通过web页面接口来访问。您提到的 fetchCategoryOpenTorrentList 接口，目前要求如下：
1. 使用POST方法请求
2. 请求body的json内容必须包含categoryId以及分页大小，具体示例如下：
```
{
    "categoryId": 4,
    "pageParam": {
        "current": 1,
        "pageSize": 20
    }
}
```
﻿
﻿
如有更多问题， 可留下联系email，通过email沟通。
